services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: gerenciamento-de-tarefas
